### ISSUE TITLE
jailbreakcode usage

### ISSUE THREAD

**Issue by SinHanYang** [UCSB-NLP-Chang/SelfDenoise#1]
Hi, thanks for your repo. I was wondering what is the usage of the new folder "jailbreakcode". I can not find the relation between the new folder and the original paper & codebase. Thanks!

**Comment by Question406** [comment]
Hi, thanks for following our repo.

Previously, we applied self-denoise to defend against LLM jailbreak attacks, and this folder contains the code for jailbreak experiments. We will update the paper and the README soon.

**Comment by SinHanYang** [comment]
Thanks for your reply. Looking forward to the paper.

**Comment by SinHanYang** [comment]
Hi, I notice that this repo doesn't have a license. 
May I use this repo for my own research project? I will cite the paper. Thanks.
